name: flutter_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # GetX工具 https://pub.dev/packages/get/install
  get:
    ^4.3.8
    # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0
  # Loading插件 https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.3
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.1
  # JSON解析 https://pub.dev/packages/json_serializable
  json_serializable: ^4.1.4
  json_annotation: ^4.0.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.3
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.1.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/lianyagang/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2 # flutter_swiper很久不维护，可以使用空安全版本：flutter_swiper_null_safety
  # 启动URL的插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.12
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.8.4+4
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.6.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.3.1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.4
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.2.0
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^2.0.0-nullsafety.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.1.0+1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.0.1
  # App Shortcuts https://github.com/flutter/plugins/tree/master/packages/quick_actions
  quick_actions: 0.6.0+7
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 3.1.1
  # 改变桌面端窗口大小(MacOS/Linux/Windows) https://github.com/mix1009/desktop_window
  desktop_window: 0.4.0
  # demo 用到的库
  # 刮刮卡 https://github.com/vintage/scratcher
  scratcher: ^2.1.0
  # 动画效果 https://github.com/xvrh/lottie-flutter
  lottie: ^1.2.1
  # 跑马灯 https://pub.dev/packages/marquee
  marquee: ^2.2.0
  # badges 角标 https://pub.dev/packages/badges
  badges: ^2.0.2
  # 网易云信
#  nim_core: ^1.0.0-rc.20

dev_dependencies:
  build_runner: ^2.1.5
  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https:/w.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/state/
    - assets/images/login/
    - assets/lottie/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
